# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathon',
            name='lat',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='lon',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
