# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 01:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackathons', '0004_hackathon_pastdue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hackathon',
            name='pastDue',
        ),
    ]
